# Local development environment with PostgreSQL
# This file is only for local development. Production uses AWS RDS.
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: meetlyomnidb
      POSTGRES_USER: meetlyomni_dev
      POSTGRES_PASSWORD: DevPassword123!
      POSTGRES_SHARED_BUFFERS: 512MB
      POSTGRES_MAX_CONNECTIONS: 20
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meetlyomni_dev -d meetlyomnidb"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./src/MeetlyOmni.Api
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=meetlyomnidb
      - DB_USER=meetlyomni_dev
      - DB_PASS=DevPassword123!
      - ConnectionStrings__MeetlyOmniDb=Host=db;Port=5432;Database=meetlyomnidb;Username=meetlyomni_dev;Password=DevPassword123!
    ports:
      - "5000:80"
    volumes:
      - ./src/MeetlyOmni.Api:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    working_dir: /app
    command: sh -c "dotnet ef database update && dotnet watch run --urls=http://0.0.0.0:80"
    mem_limit: 2g

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    mem_limit: 512m

volumes:
  postgres_data:
