
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src


COPY ./MeetlyOmni.sln ./
COPY ./src/MeetlyOmni.Api/*.csproj ./src/MeetlyOmni.Api/

RUN dotnet restore ./src/MeetlyOmni.Api/MeetlyOmni.Api.csproj


COPY . .


RUN dotnet publish ./src/MeetlyOmni.Api/MeetlyOmni.Api.csproj \
    -c Release -o /app/publish /p:UseAppHost=false



FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "MeetlyOmni.Api.dll"]