services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-meetlyomni}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_SHARED_BUFFERS: 512MB
      POSTGRES_MAX_CONNECTIONS: 20
    ports:
      - "5432:5432"
    mem_limit: 2g
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build:
      context: .
      dockerfile: src/MeetlyOmni.Api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_NAME=${DB_NAME:-meetlyomni}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${DB_PASS:-postgres}
      - ConnectionStrings__MeetlyOmniDb=Host=db;Port=5432;Database=${DB_NAME:-meetlyomni};Username=${DB_USER:-postgres};Password=${DB_PASS:-postgres}
      - Database__ApplyMigrationsOnStartup=true
      - Database__SeedOnStartup=true
    ports:
      - "5000:8080"
    mem_limit: 2g

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    mem_limit: 512m