name: CICD-Dev-AWS

on:
  push:
    branches: [dev, devops/leonard]
  pull_request:
    branches: [dev]
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0
  SOLUTION_PATH: ./MeetlyOmni.sln
  API_PROJECT: src/MeetlyOmni.Api/MeetlyOmni.Api.csproj
  DOCKERFILE: ./src/MeetlyOmni.Api/Dockerfile-2
  CONTEXT: .
  TAG_ENV: dev
  REPO: meetlyomni-backend
  ECR_URI: 034362033405.dkr.ecr.ap-southeast-2.amazonaws.com/meetlyomni-backend
  ECR_REPO: meetlyomni-backend
  AWS_REGION: ap-southeast-2
  ECS_TASK_FAMILY: meetlyomniapi-task
  ECS_CLUSTER: meetlyomniapi-cluster
  ECS_SERVICE: meetlyomniapi-svc

jobs:
  CI:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          # cache: true

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} -c Release --no-restore

      - name: Test (unit)
        run: dotnet test src/MeetlyOmni.Unit.tests/MeetlyOmni.Unit.tests.csproj -c Release --no-build

      - name: Test (integration)
        env:
          BASE_URL: http://localhost:7011
        run: dotnet test src/MeetlyOmni.IntegrationTests/MeetlyOmni.IntegrationTests.csproj -c Release --no-build
        continue-on-error: true

  build_and_push_image:
    runs-on: ubuntu-latest

    environment: dev
    needs: CI
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          TAG_SHA=${GITHUB_SHA::7}
          docker build \
            -f "${{ env.DOCKERFILE }}" \
            -t "${{ env.ECR_URI }}:${TAG_SHA}" \
            -t "${{ env.ECR_URI }}:${{ env.TAG_ENV }}" \
            "${{ env.CONTEXT }}"

      - name: Push Docker images
        run: |
          TAG_SHA=${GITHUB_SHA::7}
          docker push "${{ env.ECR_URI }}:${TAG_SHA}"
          docker push "${{ env.ECR_URI }}:${{ env.TAG_ENV }}"

  deploy_ecs:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    environment: dev
    env:
      CONTAINER_NAME: app # 对应 taskdef.json 里的 name
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      # 方式A：用上游产物
      # - name: Pick image uri from previous job
      #   id: img
      #   run: echo "uri=${{ needs.build_and_push_image.outputs.image_uri }}" >> "$GITHUB_OUTPUT"

      - name: Generate Image URI
        id: img
        run: echo "uri=${ECR_URI}:${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Render task definition with new image
        id: render
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/taskdef.json
          container-name: app
          image: ${{ steps.img.outputs.uri }}

      - name: Deploy to ECS service (rolling update)
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

